package com.gameapp.gameapp;

import android.graphics.Canvas;
import android.util.Log;
import android.view.SurfaceHolder;

/** The MainThread class keeps the game running once "New Game" is selected from the main menu (the MainActivity)
 * It is generated by the Screen class and runs until the game is over (player dies or wins) or the application quits
 * Here is where the Game States should be created, such as Game, In-Game Menu, and DeathScreen states
 */

public class MainThread extends Thread {

    private static final String TAG = MainThread.class.getSimpleName();

    //Main components
    private SurfaceHolder surfaceHolder;
    private Screen screen; //Primary class
    public static Canvas canvas;

    //FPS
    private int FPS = 30;
    private double averageFPS;

    private boolean running;

    public void setRunning(boolean running) {
        this.running = running;
    }

    public MainThread(SurfaceHolder surfaceHolder, Screen screen) {
        super();
        this.surfaceHolder = surfaceHolder;
        this.screen = screen;
    }

    @Override
    public void run() {
        //Variable for keeping track of time and FPS
        long startTime;
        long timeMillis;
        long waitTime;
        long totalTime = 0;
        int frameCount = 0;
        long targetTime = 1000/FPS;

        //Others
        long tickCount = 0L;
        Log.d(TAG, "Starting game loop");
        while (running) {
            tickCount++;

            startTime = System.nanoTime();
            canvas = null;

            //lock canvas
            try {
                canvas = this.surfaceHolder.lockCanvas();
                synchronized (surfaceHolder) {
                    screen.update();
                    screen.draw(canvas);
                }
            } catch(Exception e) {}

            finally {
                if (canvas != null) {
                    try {
                        surfaceHolder.unlockCanvasAndPost(canvas);
                    }
                    catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

            timeMillis = (System.nanoTime() - startTime) / 1000000;
            waitTime = targetTime - timeMillis;

            try {
                this.sleep(waitTime);
            } catch(Exception e) {}

            totalTime += System.nanoTime();
            frameCount++;

            if (frameCount == FPS) {
                averageFPS = 1000 / (totalTime/frameCount)/1000000;
                frameCount = 0;
                totalTime = 0;
                System.out.println(averageFPS);
            }
        }
        Log.d(TAG, "Game loop executed " + tickCount + " times");
    }
}
